services:
  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  # API Instance 1
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: rinha-backend-node:latest
    container_name: rinha-api-1
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rinha_backend
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - PROCESSOR_TOKEN=123
      - MAX_RETRY_ATTEMPTS=3
      - SIMULATION_MODE=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  # API Instance 2
  api-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: rinha-backend-node:latest
    container_name: rinha-api-2
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rinha_backend
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - PROCESSOR_TOKEN=123
      - MAX_RETRY_ATTEMPTS=3
      - SIMULATION_MODE=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rinha-postgres
    environment:
      - POSTGRES_DB=rinha_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha_backend"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  # Redis for Queue
  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

volumes:
  postgres_data:
  redis_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
